package com.athena.mis

import com.athena.mis.application.entity.AppDbInstance

/**
 * Created by Qutub on 10/25/2015.
 */
class DataExportDto {
    long id                         // Primary Key (Auto Generated By it's own sequence)
    long entityTypeId
    String name                     // Unique Name within Company
    String columnSeparator          // column separator e.g. (,)
    String escapeCharacter          // e.g. (\)
    String quoteCharacter           // e.g ("\"")
    int recordPerBatch              // count of record per batch for DB to DB
    long maxRecordPerFile
    long dataFeedTypeId             // type of data feed i.e. Text or CSV (SystemEntity.id)
    long dataFeedTypeTxtId
    long dataFeedTypeCsvId
    String dataFeedPath                 // absolute path of file if export db to file
    long companyId                  // Company.id
    String url
    String fileExt
    String entityDomainName
    String schemaName
    List lstTableName
    List lstSchema
    List lstLogCount
    List lstFieldValue
}
