package com.athena.mis.application.model

class ListBankActionServiceModel {
    public static final String SQL_LIST_BANK_MODEL = """
    DROP TABLE IF EXISTS list_bank_action_service_model;
    DROP VIEW IF EXISTS list_bank_action_service_model;
    CREATE OR REPLACE VIEW list_bank_action_service_model AS
        SELECT
            b.id,
            b.version,
            b.name,
            b.code,
            b.is_system_bank,
            b.company_id,
            b.country_id,
            c.name country_name
        FROM app_bank b
        LEFT JOIN app_country c ON b.country_id= c.id
    """

    long id               // primary key (Auto generated by its own sequence)
    long version          // entity version in the persistence layer
    String name           // Unique code within a company
    String code           // Unique code within a company
    boolean isSystemBank  // flag for system bank
    long companyId        // Company.id
    long countryId        // AppCountry.id
    String countryName    // AppCountry.name

    static mapping = {
        cache usage: "read-only"
    }
}
