package com.athena.mis.application.model

class ListAppUserEntityActionServiceModel {
    public static final String SQL_APP_USER_ENTITY_MODEL = """
    DROP TABLE IF EXISTS list_app_user_entity_action_service_model;
    DROP VIEW IF EXISTS list_app_user_entity_action_service_model;
    CREATE OR REPLACE VIEW list_app_user_entity_action_service_model AS
        SELECT
            aue.id,
            aue.app_user_id,
            aue.entity_type_id,
            aue.entity_id,
            aue.company_id,
            au.username as user_name
        FROM app_user_entity aue
        LEFT JOIN app_user au ON au.id = aue.app_user_id
    """

    long id                         // primary key (Auto generated by its own sequence)
    long version
    long appUserId                  // AppUser.id
    long entityTypeId               // SystemEntity.id (e.g. Project, Inventory, Customer etc)
    long entityId                   // id of corresponding entity (e.g. Project.id, Inventory.id)
    long companyId                  // Company.id
    String userName

    static mapping = {
        version false
        cache usage: "read-only"
    }
}

