package com.athena.mis.application.model

class ListSupplierActionServiceModel {
    public static final String SQL_LIST_SUPPLIER_MODEL = """
    DROP TABLE IF EXISTS list_supplier_action_service_model;
    DROP VIEW IF EXISTS list_supplier_action_service_model;
    CREATE OR REPLACE VIEW list_supplier_action_service_model AS
        SELECT
            s.id,
            s.version,
            s.name,
            s.address,
            s.account_name,
            s.bank_name,
            s.bank_account,
            s.item_count,
            s.company_id,
            s.supplier_type_id,
            se.key as supplier_type_name
        FROM supplier s
        LEFT JOIN system_entity se ON se.id = s.supplier_type_id
    """
    long id                 // primary key (Auto generated by its own sequence)
    long version             // entity version in the persistence layer
    String name             // Unique name within a company
    String address          // Supplier Address
    String accountName      // Supplier Bank Account Name
    String bankName         // Supplier Bank Name
    String bankAccount      // Supplier Bank Account Number
    int itemCount           // no of item for this supplier
    long supplierTypeId     // SystemEntity.id (e.g. Material Provider, Service Provider etc)
    long companyId          // Company.id
    String supplierTypeName

    static mapping = {
        cache usage: "read-only"
    }
}
