package com.athena.mis.application.model

class ListAllAppUserActionServiceModel {

    public static final String SQL_LIST_ALL_APP_USER_MODEL = """
        DROP TABLE IF EXISTS list_all_app_user_action_service_model;
        DROP VIEW IF EXISTS list_all_app_user_action_service_model;
        CREATE OR REPLACE VIEW list_all_app_user_action_service_model AS
        SELECT au.id, au.version, au.login_id, au.username, au.enabled, au.account_locked, au.account_expired,
        au.is_power_user, au.is_config_manager, au.cell_number, au.ip_address, au.is_disable_password_expiration,
        company.name AS company_name, au.is_switchable, au.is_reserved
        FROM app_user au
        LEFT JOIN company ON company.id = au.company_id
        WHERE au.is_company_user = FALSE
        AND au.is_reseller = FALSE
    """

    long id                                 // primary key (Auto generated by its own sequence)
    long version                            // entity version in the persistence layer
    String loginId                          // user login name (unique within a company)
    String username                         // user name of AppUser
    boolean enabled                         // flag to enable AppUser
    boolean accountExpired                  // flag to determine is account expired or not
    boolean accountLocked                   // flag to determine is account locked or not
    boolean isPowerUser                     // flag to determine power user
    boolean isConfigManager                 // flag to determine config manager
    String cellNumber                       // AppUser cell Number
    String ipAddress                        // AppUser IP address
    boolean isDisablePasswordExpiration     // if true then AppUser password will not expire
    String companyName                      // Company.name
    boolean isSwitchable                    // AppUser.isSwitchable
    boolean isReserved                      // AppUser.isReserved

    static mapping = {
        cache usage: "read-only"
    }
}
