package com.athena.mis.application.model

class ListContentCategoryActionServiceModel {
    public static final String SQL_LIST_CONTENT_CATEGORY_MODEL = """
    DROP TABLE IF EXISTS list_content_category_action_service_model;
    DROP VIEW IF EXISTS list_content_category_action_service_model;
    CREATE OR REPLACE VIEW list_content_category_action_service_model AS
        SELECT
            category.id,
            category.version,
            category.name,
            category.width,
            category.height,
            category.max_size,
            category.extension,
            category.content_type_id,
            category.company_id,
            type.key AS content_type_name,
            category.is_reserved
        FROM content_category category
        LEFT JOIN system_entity type ON type.id = category.content_type_id
    """

    long id                         // primary key (Auto generated by its own sequence)
    long version                     // entity version in the persistence layer
    String name                     // unique for content type -- Content Category Name(Signature, Image, PhotoId, Drawing, Archive etc.)
    long contentTypeId              // SystemEntity.id (Document, Image)
    long maxSize                    // Maximum file size (e.g : 1024*1024*1, 1024*1024*5 etc.)
    int width                       // width of the Content(e.g : 512 etc.)
    int height                      // height of the Content(e.g : 1024 etc.)
    String extension        /* Coma separated Extension of the content (e.g : doc, excel, pdf, png, jpeg, gif etc)
                               If extension is defined then Content should be exactly as declared,
                               Otherwise Content could be any type like doc, xls, pdf, png, jpeg, gif etc.
                            */

    long companyId       // Company.id
    String contentTypeName
    boolean isReserved

    static mapping = {
        cache usage: "read-only"
    }
}
