package com.athena.mis.application.model

class ListAppUserActionServiceModel {

    public static final String SQL_LIST_APP_USER_MODEL = """
    DROP TABLE IF EXISTS list_app_user_action_service_model;
    DROP VIEW IF EXISTS list_app_user_action_service_model;
    CREATE OR REPLACE VIEW list_app_user_action_service_model AS
        SELECT
            au.id,
            au.version,
            au.login_id,
            au.username,
            au.enabled,
            au.account_expired,
            au.account_locked,
            au.cell_number,
            au.password,
            au.ip_address,
            au.is_disable_password_expiration,
            au.company_id,
            au.employee_id,
            employee.full_name AS employee_name,
            au.gender_id,
            au.email
        FROM app_user au
        LEFT JOIN app_employee employee ON employee.id = au.employee_id
        WHERE au.is_company_user = FALSE
        AND au.is_reseller = FALSE AND au.is_system_user = FALSE
    """

    long id                                 // primary key (Auto generated by its own sequence)
    long version                            // entity version in the persistence layer
    String loginId                          // user login name (unique within a company)
    String username                         // user name of AppUser
    boolean enabled                         // flag to enable AppUser
    boolean accountExpired                  // flag to determine is account expired or not
    boolean accountLocked                   // flag to determine is account locked or not
    String cellNumber                       // AppUser cell Number
    String password                         // password of AppUser
    String ipAddress                        // AppUser IP address
    boolean isDisablePasswordExpiration     // if true then AppUser password will not expire
    long companyId                          // Company.id
    long employeeId                         // AppEmployee.id
    String employeeName                     // AppEmployee.name
    long genderId                           // AppUser.genderId
    String email                            // AppUser.email

    static mapping = {
        cache usage: "read-only"
    }
}
