package com.athena.mis.application.model

class ListAppShellScriptActionServiceModel {

    public static final String SQL_LIST_APP_SHELL_SCRIPT_MODEL = """
        DROP TABLE IF EXISTS list_app_shell_script_action_service_model;
        DROP VIEW IF EXISTS list_app_shell_script_action_service_model;
        CREATE OR REPLACE VIEW list_app_shell_script_action_service_model AS
        SELECT
            ss.id,
            ss.name,
            ss.version,
            ss.script,
            ss.server_instance_id,
            ss.script_type_id,
            ss.plugin_id,
            ss.company_id,
            ss.last_executed_on,
            ss.number_of_execution,
            ss.is_reserved,
            CASE WHEN ss.name = 'Backup Script' THEN 'AppBackupShellScriptJob'
            WHEN ss.name = 'Maintenance Script' THEN 'AppMaintenanceShellScriptJobActionService'
            WHEN ss.name = 'Backup SQL' THEN 'AppBackupSqlScriptJobActionService'
            WHEN ss.name = 'Maintenance SQL' THEN  'AppMaintenanceSqlScriptJobActionService'
            ELSE ' '
            END transaction_code
        FROM app_shell_script ss
    """

    long id                     // primary key (Auto generated by its own sequence)
    long version                // entity version in the persistence layer
    String name                 // Name of AppShellScript (unique)
    String script               // script of AppShellScript
    long serverInstanceId       // if script type shell AppServerInstance.id, if script type sql AppDbInstance.id
    long scriptTypeId           // SystemEntity.id (Sell, SQL)
    long companyId              // Company.id
    int pluginId                // id of plugin (e.g. 1 for Application, 13 for Document etc.)
    Date lastExecutedOn         // Script or sql executed DateTime
    int numberOfExecution       // count of execution
    String transactionCode      // action name
    boolean isReserved          // reserved script flag

    static mapping = {
        cache usage: "read-only"
    }
}
