package com.athena.mis.application.model

class ListAppVendorActionServiceModel {

    public static final String SQL_VENDOR_MODEL = """
        DROP TABLE IF EXISTS list_app_vendor_action_service_model;
        DROP VIEW IF EXISTS list_app_vendor_action_service_model;
        CREATE OR REPLACE VIEW list_app_vendor_action_service_model AS
        SELECT
            v.id,
            v.version,
            v.name,
            v.driver,
            v.description,
            v.company_id,
            v.sequence,
            v.db_type_id,
            v.vendor_id,
            dbType.key AS db_type_name
        FROM vendor v
        LEFT JOIN system_entity dbType ON dbType.id = v.db_type_id
    """

    long id                     // primary key (Auto generated by its own sequence)
    long version                // entity version in the persistence layer
    String name                 // Unique name within a dbTypeId and company
    String driver               // database driver
    String description          // description of vendor
    long dbTypeId               // SystemEntity.id (Source or Target)
    long vendorId               // SystemEntity.id (Postgres, Oracle, MySql, MSSQL, Redshift)
    int sequence                // object sequence order
    long companyId              // Company.id
    String dbTypeName

    static mapping = {
        cache usage: "read-only"
    }
}
