package com.athena.mis.application.model

class ListAppCompanyUserActionServiceModel {

    public static final String SQL_LIST_APP_COMPANY_USER_MODEL = """
    DROP TABLE IF EXISTS list_app_company_user_action_service_model;
    DROP VIEW IF EXISTS list_app_company_user_action_service_model;
    CREATE OR REPLACE VIEW list_app_company_user_action_service_model AS
        SELECT
            au.id,
            au.version,
            au.username,
            au.login_id,
            au.enabled,
            au.account_locked,
            au.account_expired,
            au.cell_number,
            au.ip_address,
            au.password,
            au.company_id as app_user_company_id,
            company.name AS company_name
        FROM app_user au
        LEFT JOIN company ON company.id = au.company_id
        WHERE au.is_company_user = TRUE
    """
    long id                         // primary key (Auto generated by its own sequence)
    long version                    // entity version in the persistence layer
    String username                 // user name of AppUser
    String loginId                  // user login name (unique within a company)
    boolean enabled                 // flag to enable AppUser
    boolean accountLocked           // flag to determine is account locked or not
    boolean accountExpired          // flag to determine is account expired or not
    String cellNumber               // AppUser cell Number
    String ipAddress                // AppUser IP address
    String password                 // password of AppUser
    long appUserCompanyId           // Company.id
    String companyName              // Company.name

    static mapping = {
        cache usage: "read-only"
    }
}
