package com.athena.mis.application.model

class ListItemTypeActionServiceModel {
    public static final String SQL_LIST_ITEM_TYPE_MODEL = """
    DROP TABLE IF EXISTS list_item_type_action_service_model;
    DROP VIEW IF EXISTS list_item_type_action_service_model;
    CREATE OR REPLACE VIEW list_item_type_action_service_model AS
        SELECT
            it.id,
            it.version,
            it.name,
            it.company_id,
            it.category_id,
            se.key as category_name
        FROM item_type it
        LEFT JOIN system_entity se ON se.id = it.category_id
    """

    long id              // primary key (Auto generated by its own sequence)
    long version          // entity version in the persistence layer
    String name          // Unique name within a company
    long categoryId      // SystemEntity.id (Inventory, NonInventory, FixedAsset)
    long companyId       // Company.id
    String categoryName    //

    static mapping = {
        cache usage: "read-only"
    }
}
