package com.athena.mis.application.model

class ListSupplierItemActionServiceModel {
    public static final String SQL_LIST_SUPPLIER_ITEM_MODEL = """
    DROP TABLE IF EXISTS list_supplier_item_action_service_model;
    DROP VIEW IF EXISTS list_supplier_item_action_service_model;
    CREATE OR REPLACE VIEW list_supplier_item_action_service_model AS
        SELECT
            si.id,
            si.version,
            si.supplier_id,
            si.item_id,
            si.company_id,
            item.name as item_name,
            item.code,
            item.unit,
            item.item_type_id AS item_type_id,
            it.name AS item_type_name
        FROM supplier_item si
        LEFT JOIN item ON item.id = si.item_id
        LEFT JOIN item_type it ON it.id = item.item_type_id
    """
    long id               // primary key (Auto generated by its own sequence)
    long version          // entity version in the persistence layer
    long supplierId       // Supplier.id (Parent)
    long itemId           // Item.id
    long itemTypeId       // Item.itemTypeId
    String code
    String unit
    long companyId        // Company.id
    String itemTypeName
    String itemName

    static mapping = {
        cache usage: "read-only"
    }
}
