package com.athena.mis.application.entity

class AppFaq {

    public static final String DELETE_TEST_DATA_QUERY = """ DELETE FROM app_faq WHERE id < 0 and company_id = :companyId """

    public static final String DEFAULT_SORT_FIELD = "id"

    long id                     // primary key (Auto generated by its own sequence)
    long version                // entity version in the persistence layer
    long entityTypeId           // SystemEntity.id (Customers, Task)
    long entityId               // customers.id, task.id etc
    String question                 // comment body
    String answer                 // comment body
    long createdBy              // AppUser.id
    Date createdOn              // Object creation DateTime
    long updatedBy              // AppUser.id
    Date updatedOn              // Object updated DateTime
    long companyId              // Company.id
    int pluginId                // plugin id e.g : 1 for Application, 9 for Exchange House etc.

    static constraints = {
        entityTypeId(nullable: false)
        entityId(nullable: false)
        question(nullable: false, blank: false)
        answer(nullable: false, blank: false, maxSize: 5000)
        createdBy(nullable: false)
        createdOn(nullable: false)
        updatedOn(nullable: true)
        updatedBy(nullable: false)
        companyId(nullable: false)
        pluginId(nullable: false)
    }

    static mapping = {
        id generator: 'sequence', params: [sequence: 'app_faq_id_seq']
        entityTypeId index: 'app_faq_entity_type_id_idx'
        entityId index: 'app_faq_entity_id_idx'
        pluginId index: 'app_faq_plugin_id_idx'
        createdBy index: 'app_faq_created_by_idx'
        companyId index: 'app_faq_company_id_idx'
        updatedBy index: 'app_faq_updated_by_idx'
    }

    public String getAnswer() {
        return answer.length() > 5000 ? answer.substring(0, 4999) : answer
    }
}
