package com.athena.mis.application.entity

/**
 * <p>
 * <strong>Module:</strong> Application </br>
 * <strong>Purpose:</strong> Contains AppGroup mapping relation with different entity.
 * AppGroupEntity has association with few other domains as listed below.
 * </p>
 *
 * <p><strong>Local Reference:</strong> Has-a relationship with other domains:</p>
 * <ul>
 *     <li>{@link com.athena.mis.application.entity.AppGroup#id as groupId}</li>
 *     <li>{@link com.athena.mis.application.entity.SystemEntity#id as entityTypeId}</li>
 *     <li>{@link com.athena.mis.application.entity.Company#id as companyId}</li>
 * </ul>
 *
 */
class AppGroupEntity {
    long id             // primary key (Auto generated by its own sequence)
    long groupId        // AppGroup.id
    long entityTypeId   // SystemEntity.id
    long entityId       // id of corresponding entity
    long companyId      // Company.id

    static constraints = {
        groupId(nullable: false)
        entityTypeId(nullable: false)
        entityId(nullable: false)
        companyId(nullable: false)
    }

    static mapping = {
        id generator: 'sequence', params: [sequence: 'app_group_entity_id_seq']
        version false
        groupId index: 'app_group_entity_group_id_idx'
        entityTypeId index: 'app_group_entity_entity_type_id_idx'
        entityId index: 'app_group_entity_entity_id_idx'
        companyId index: 'app_group_entity_company_id_idx'

        // unique index on "group_id", "entity_id" and "entity_type_id" using AppGroupEntityService.createDefaultSchema()
        // <domain_name><property_name_1><property_name_2><property_name_3>idx
    }
}
