package com.athena.mis.application.entity

class AppMessage {

    long id                         // primary key (Auto generated by its own sequence)
    long version                    // entity version in the persistence layer
    long appMailId                  // AppMail.id
    long appUserId                  // AppUser.id
    boolean isRead                  // true indicate mail is read
    Date createdOn                  //
    long companyId                  // Company.id

    String subject                  // AppMail.subject
    String senderName               // AppUser.username
    long senderId                   // AppUser.id
    String body                     // body of message(AppMail.body)

    static constraints = {
        subject(nullable: false)
        senderName(nullable: false)
        senderId(nullable: false)
        appMailId(nullable: false)
        appUserId(nullable: false)
        isRead(nullable: false)
        body(nullable: false, maxSize: 2040)
    }

    static mapping = {
        id generator: 'sequence', params: [sequence: 'app_message_id_seq']
        companyId index: 'app_message_company_id_idx'
        appMailId index: 'app_message_app_mail_id_idx'
        appUserId index: 'app_message_app_user_id_idx'
    }
}
