package com.athena.mis.application.entity

class AppUserDetails {

    public static final int ABOUT_ME_MAX_LENGTH = 5000

    long id                         // Primary Key (Auto Generated By it's own sequence)
    long version                    // entity version in the persistence layer

    long userId
    Date dateOfBirth
    String address
    String nationalId
    String webUrl
    String facebookUrl
    String aboutMe
    Date lastLogin
    String lastLogIp
    String lastLogOs
    long point

    long companyId                  // Company.id

    long createdBy                  // AppUser.id
    Date createdOn                  // Date of creation
    long updatedBy                  // AppUser.id
    Date updatedOn                  // Date of update

    static constraints = {
        dateOfBirth(nullable: true)
        address(nullable: true)
        nationalId(nullable: true)
        webUrl(nullable: true)
        facebookUrl(nullable: true)
        aboutMe(nullable: true, maxSize: ABOUT_ME_MAX_LENGTH)
        lastLogin(nullable: true)
        lastLogIp(nullable: true)
        lastLogOs(nullable: true)
        updatedBy(nullable: false)
        updatedOn(nullable: true)
    }

    static mapping = {
        dateOfBirth type: "date"

        id generator: 'sequence', params: [sequence: 'app_user_details_id_seq']
        userId index: 'app_user_details_user_id_idx'
        companyId index: 'app_user_details_company_id_idx'
        createdBy index: 'app_user_details_created_by_idx'
        updatedBy index: 'app_user_details_updated_by_idx'
    }

    public String getAboutMe() {
        return aboutMe && aboutMe.length() > ABOUT_ME_MAX_LENGTH ? aboutMe.substring(0, ABOUT_ME_MAX_LENGTH - 1) : aboutMe
    }

    public String getAddress() {
        return address && address.length() > 255 ? address.substring(0, 255 - 1) : address
    }
}
