package com.athena.mis.application.entity

/**
 * <p>
 * <strong>Module:</strong> Application </br>
 * <strong>Purpose:</strong> Determines access control of all features.
 * </p>
 *
 */
class RequestMap {

    public static final String DEFAULT_SORT_FIELD = "url"

    long id                    // primary key (Auto generated by its own sequence)
    int version                // entity version in the persistence layer
    String url                 // url (e.g : '/company/show')
    String configAttribute     // comma separated Role authority
    String featureName         // feature name (e.g: Show for Company)
    Integer pluginId           // plugin id  (e.g: for Application 1, for Budget 3 etc.)
    String transactionCode     // unique transaction code (e.g: APP-10)
    Boolean isViewable         // True for show, False for rest
    Boolean isCommon           // determine if this feature is common for all company

    static mapping = {
        id generator: 'sequence', params: [sequence: 'request_map_id_seq']

        // unique index on "transaction_code" and "url" using RequestMapService.createDefaultSchema()
        // <domain_name><property_name_1><property_name_2>idx
    }

    static constraints = {
        url(blank: false)
        transactionCode(blank: false)
        configAttribute(size: 1..5000)
        featureName(nullable: true)
    }
}
