package com.athena.mis.application.entity

class Vendor {

    public static final String DEFAULT_SORT_FIELD = "name"

    long id                     // primary key (Auto generated by its own sequence)
    long version                // entity version in the persistence layer
    String name                 // Unique name within a dbTypeId and company
    String driver               // database driver
    String description          // description of vendor
    long dbTypeId               // SystemEntity.id (Source or Target)
    long vendorId               // SystemEntity.id (Postgres, Oracle, MySql, MSSQL, Redshift)
    int sequence                //
    byte[] smallImage           // vendor small image
    byte[] thumbImage           // vendor thumb image

    long companyId              // Company.id
    long createdBy              // AppUser.id
    Date createdOn              // Object creation DateTime
    long updatedBy              // AppUser.id
    Date updatedOn              // Object Updated DateTime

    static constraints = {
        name(nullable: false)
        driver(nullable: false)
        dbTypeId(nullable: false)
        vendorId(nullable: false)
        sequence(nullable: false)
        smallImage(nullable: true)
        thumbImage(nullable: true)
        description(nullable: true, maxSize: 255)
        companyId(nullable: false)
        createdBy(nullable: false)
        createdOn(nullable: false)
        updatedBy(nullable: false)
        updatedOn(nullable: true)
    }

    static mapping = {
        id generator: 'sequence', params: [sequence: 'vendor_id_seq']
        dbTypeId index: 'vendor_db_type_id_idx'
        vendorId index: 'vendor_vendor_id_idx'
        companyId index: 'vendor_company_id_idx'
        createdBy index: 'vendor_created_by_idx'
        updatedBy index: 'vendor_updated_by_idx'
    }

    public String getDescription() {
        return description && description.length() > 255 ? description.substring(0, 254) : description
    }
}
